### ISSUE TITLE
Arguments for function for design-based estimation (createDBestim) based on master table (rdbesEstimObj)

### ISSUE THREAD

**Issue by nmprista** [ices-tools-dev/icesRDBES#24]
Developing a function (doDBestimation) to produce simple design-based estimates of totals starting from "master table" (rdbesEstimObj). See more details WKRDB-EST2.

Function to have as arguments: 
data: rdbesEstimObj
estimateType: "total", "mean", ...
pointEstimator: "Unbiased", "Ratio", ...
varEstimator:  = "WRonPSUviaPik", "HT", ...
stage: 0 (to DE), 1 (to su1), 2 (to su2), ...
domainOfInterest: e.g., SAarea

and output point estimates and variances alongside documentation of procedures used

**Comment by nmprista** [comment]
#18 #15  please consider this

**Comment by rix133** [comment]
**[doEstimationForAllStrata](https://github.com/ices-tools-dev/RDBEScore/blob/dev/R/doEstimationForAllStrata.R)** has been agreed to be the function to be the  estimation function instead of https://github.com/ices-tools-dev/RDBEScore/issues/15  and https://github.com/ices-tools-dev/RDBEScore/issues/24
