### ISSUE TITLE
R CMD Check returns errors

### ISSUE THREAD

**Issue by ptrptr** [ices-tools-dev/icesRDBES#44]
Running devtools::check() returns errors.

**Comment by nicolas-tku** [comment]
Backtrace:
    ▆
 1. └─devtools::check()
 2.   └─devtools::as.package(pkg)
 3.     └─devtools::package_file(path = x)
 4.       └─cli::cli_abort(c("Could not find package root.", i = "Is {.path {base_path}} inside a package?"))
 5.         └─rlang::abort(...)

**Comment by nicholascarey** [comment]
These checks can be incredibly picky and annoying and usually the last thing you do before release. I will work my way through them periodically.

**Comment by nicholascarey** [comment]
Most are fixed, but there are bound to be others that will occur. 

There is one related to a vignette i still have to figure out. 

For record: 
- Most common issue is "no visible binding for global variable..". No idea why this happens. Have read about it so many times  - still don't get it. Fixed by adding some text in `utils.R` files - see there. 
- "no visible binding for global function.." - usually caused by using `package::` or not specifying a package for a function that has a name conflict across packages. Fix by either putting in roxygen tags `@import package_name` or if only using a single function `@importFrom package_name function_name`

**Comment by ptrptr** [comment]
Fixed for now
